# fly.toml app configuration file generated for rslts on 2023-05-30T19:45:11-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rslts"
primary_region = "sjc"

[[mounts]]
  source = "rslts_db"
  destination = "/rslts"

[http_service]
  internal_port = 3030
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[checks]
  [checks.main]
    method = "get"
    path = "/healthcheck"
    port = 3030
    type = "http"
